import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";
import {ToastContainer} from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";

import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import Header from "@/src/components/header";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children, params: {locale}}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    const dir = locale == 'fa' ? 'rtl' : 'ltr';
    const messages = await getMessages();
    return (
        <html lang={locale} dir={dir}>
        <body className={`${inter.className} bg-white dark:bg-black`}>
        <NextIntlClientProvider messages={messages}>
            <Header/>
            {children}
            <ToastContainer/>
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
